import asyncio
import aiohttp

# WAF signatures based on response headers and body patterns
WAF_SIGNATURES = [
    {
        "name": "Cloudflare",
        "headers": {"Server": "cloudflare", "CF-RAY": None},
        "body": r"cloudflare",
        "status": [403, 503],
    },
    {
        "name": "AWS WAF / CloudFront",
        "headers": {"X-Cache": "Error from cloudfront", "Via": "cloudfront"},
        "body": r"aws",
        "status": [403],
    },
    {
        "name": "Sucuri",
        "headers": {"X-Sucuri-ID": None, "X-Sucuri-Cache": None},
        "body": r"sucuri",
        "status": [403],
    },
    {
        "name": "Imperva / Incapsula",
        "headers": {"X-Iinfo": None, "X-CDN": "Incapsula"},
        "body": r"incapsula|imperva",
        "status": [403],
    },
    {
        "name": "Akamai",
        "headers": {"X-Check-Cacheable": None, "Akamai-Origin-Hop": None},
        "body": r"akamai",
        "status": [403],
    },
    {
        "name": "Barracuda",
        "headers": {"X-Barracuda-Connect": None},
        "body": r"barracuda",
        "status": [400, 403],
    },
    {
        "name": "F5 BIG-IP ASM",
        "headers": {"X-Cnection": None},
        "body": r"big.?ip|f5",
        "status": [400, 403],
    },
    {
        "name": "ModSecurity",
        "headers": {"X-Mod-Security": None},
        "body": r"mod_security|modsecurity|NOYB",
        "status": [403, 501],
    },
    {
        "name": "Wordfence",
        "headers": {},
        "body": r"wordfence|generated by wordfence",
        "status": [403],
    },
    {
        "name": "Fortinet FortiWeb",
        "headers": {"X-Frame-Options": None},
        "body": r"fortiweb|fortigate",
        "status": [403],
    },
]

# Send a probe request that might trigger a WAF (common SQLi string)
PROBE_PATH = "/?id=1'%20OR%20'1'='1"


async def scan_waf(target: str, timeout: int = 5):
    import re
    results = {"detected": False, "waf": "None detected", "details": {}}

    connector = aiohttp.TCPConnector(ssl=False)
    async with aiohttp.ClientSession(connector=connector) as session:
        for url in [f"https://{target}{PROBE_PATH}", f"http://{target}{PROBE_PATH}"]:
            try:
                async with session.get(
                    url,
                    timeout=aiohttp.ClientTimeout(total=timeout),
                    allow_redirects=False,
                ) as resp:
                    headers = dict(resp.headers)
                    body = await resp.text(errors="ignore")
                    status = resp.status

                    for sig in WAF_SIGNATURES:
                        matched = False

                        # Check headers
                        for h, v in sig["headers"].items():
                            if h in headers:
                                if v is None or v.lower() in headers[h].lower():
                                    matched = True
                                    break

                        # Check body
                        if not matched and sig.get("body"):
                            if re.search(sig["body"], body, re.IGNORECASE):
                                matched = True

                        if matched:
                            results["detected"] = True
                            results["waf"] = sig["name"]
                            results["details"]["status_code"] = status
                            return results

                    # If no specific WAF matched but got a 403 with unusual headers
                    if status == 403:
                        results["detected"] = True
                        results["waf"] = "Unknown WAF (403 on probe)"
                        results["details"]["status_code"] = status

                    return results

            except Exception:
                continue

    return results
  
